# GoReleaser configuration for paw
# Documentation: https://goreleaser.com

version: 2

project_name: paw

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: paw
    main: ./cmd/paw
    binary: paw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  # Darwin archives include paw-notify.app
  - id: darwin
    formats:
      - tar.gz
    builds:
      - paw
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*
      - src: paw-notify.app
        dst: .
        strip_parent: true
    filter:
      - goos: darwin

  # Non-darwin archives (linux, windows)
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    builds:
      - paw
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*
    filter:
      - goos: linux
      - goos: windows

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactor
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

brews:
  - repository:
      owner: dongho-jung
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/dongho-jung/paw
    description: A project management system built on Claude Code
    license: MIT
    dependencies:
      - name: tmux
    install: |
      bin.install "paw"
      # Install paw-notify.app for macOS desktop notifications
      if File.exist?("paw-notify.app")
        (share/"paw").install "paw-notify.app"
      end
    post_install: |
      # Copy paw-notify.app to user's local share directory
      if File.exist?("#{share}/paw/paw-notify.app")
        user_share = "#{ENV["HOME"]}/.local/share/paw"
        mkdir_p user_share unless File.directory?(user_share)
        system "rm", "-rf", "#{user_share}/paw-notify.app"
        system "cp", "-R", "#{share}/paw/paw-notify.app", user_share
        # Remove quarantine attribute and sign
        system "xattr", "-cr", "#{user_share}/paw-notify.app"
        system "codesign", "-fs", "-", "#{user_share}/paw-notify.app"
      end
    caveats: |
      paw-notify.app has been installed to ~/.local/share/paw/

      To enable desktop notifications, you may need to:
      1. Run: paw check
      2. Grant notification permissions when prompted
    test: |
      system "#{bin}/paw", "version"

release:
  github:
    owner: dongho-jung
    name: paw
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.Tag}}"
  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install dongho-jung/tap/paw
    ```
