#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/cmd/paw/version_map.go"
VERSION="${1:-}"

if ! command -v git >/dev/null 2>&1; then
	echo "git is required to generate the version map" >&2
	exit 1
fi

tags="$(git -C "$ROOT_DIR" tag -l 'v*' --sort=version:refname)"
entries=""

if [ -n "$tags" ]; then
	while IFS= read -r tag; do
		[ -z "$tag" ] && continue
		commit="$(git -C "$ROOT_DIR" rev-list -n 1 "$tag")"
		commit_short="${commit:0:7}"
		entries="${entries}	\"$tag\": \"$commit_short\",\n"
	done <<EOF
$tags
EOF
fi

if [ -n "$VERSION" ]; then
	if ! printf '%s\n' "$tags" | grep -qx "$VERSION"; then
		commit="$(git -C "$ROOT_DIR" rev-parse HEAD)"
		commit_short="${commit:0:7}"
		entries="${entries}	\"$VERSION\": \"$commit_short\",\n"
	fi
fi

{
	echo "// Code generated by scripts/update-version-map.sh; DO NOT EDIT."
	echo ""
	echo "package main"
	echo ""
	echo "var versionCommitMap = map[string]string{"
	if [ -n "$entries" ]; then
		printf "%b" "$entries"
	fi
	echo "}"
} > "$OUT_FILE"
